### ISSUE TITLE
Could you upload the .ui file of sgui.py, please?

### ISSUE THREAD

**Issue by Huangzhiqang** [SojiroFukuda/sview-gui#6]
Hi, Developer,

I'm interested in Building GUI with PyQt, but I'm new at this. Your project provide a good example for me. I would very appreciate it  if you can upload the .ui file of sgui.py.

**Comment by jyonirou** [comment]
Hello, thanks for your interest in my package.
As you wish, I uploaded the UI file, so please find it. I hope it would be helpful for you.
